include(ExternalProject)
project(OuterBuild)

find_package(Qt5 COMPONENTS Core Widgets Charts REQUIRED)

ExternalProject_Add(ParaView
  PREFIX ParaView
  GIT_REPOSITORY https://gitlab.kitware.com/paraview/paraview.git
  GIT_TAG v5.2.0
  GIT_SHALLOW 1
  BINARY_DIR ${CMAKE_BINARY_DIR}/ParaView-build
  INSTALL_DIR ${CMAKE_BINARY_DIR}/install
  CMAKE_ARGS 
    -Wno-dev
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DPARAVIEW_USE_QTHELP:BOOL=OFF
    -DPARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION:BOOL=OFF
    -DPARAVIEW_QT_VERSION=5
    -DQt5_DIR=${Qt5_DIR}
)

ExternalPRoject_Add(Pulse
  PREFIX Pulse
  GIT_REPOSITORY https://gitlab.kitware.com/physiology/engine.git
  GIT_TAG v1.0
  GIT_SHALLOW 1
  BINARY_DIR ${CMAKE_BINARY_DIR}/Pulse-build
  INSTALL_DIR ${CMAKE_BINARY_DIR}/install
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install
    -DDOWNLOAD_BASELINES:BOOL=OFF
)

ExternalProject_Add(PhysiologyExplorer
  PREFIX PhysiologyExplorer
  DEPENDS ParaView Pulse
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}
  BINARY_DIR ${CMAKE_BINARY_DIR}/PhysiologyExplorer-build
  INSTALL_DIR ${CMAKE_BINARY_DIR}/install
  CMAKE_ARGS
    -DDO_SUPERBUILD:BOOL=OFF
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DParaView_DIR:PATH=${CMAKE_BINARY_DIR}/ParaView-build
    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install
    -DQt5_DIR=${Qt5_DIR}
)